server:
  port: ${SERVICE_PORT}

spring:
  application:
    name: notification-service
  profiles:
    include:
      - db
      - eureka
      - firebase
      - mail
      - kafka
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE