eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    fetch-registry: true
  instance:
    hostname: ${EUREKA_INSTANCE_NAME}
    non-secure-port: 80
    secure-port: 443
    secure-port-enabled: true
    non-secure-port-enabled: false
    prefer-ip-address: true
